apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-task-sync-and-wait
spec:
  params:
    - name: flags
      default: --
    - name: argocd-version
      default: v2.1.7
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap  
      - secretRef:
          name: argocd-env-secret 
  steps:
    - name: argocd-app-sync
      image: argoproj/argocd:$(params.argocd-version)
      script: |
        argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
        argocd app sync $ARGOCD_APPLICATION_NAME $(params.flags) --server $ARGOCD_SERVER --insecure
        argocd app wait $ARGOCD_APPLICATION_NAME --health $(params.flags) --server $ARGOCD_SERVER --insecure