apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: argocd-server.argocd.svc.cluster.local:443
  ARGOCD_APPLICATION_NAME: simple-app
  ARGOCD_APPLICATION_REVISION: HEAD