apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-app-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/devandi/simple-web-app.git
  - name: revision
    value: master