apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: simple-webapp-pipeline
spec:
  params:
  - name: image-tag
    type: string
  resources:
  - name: git-app-repo
    type: git
  - name: container-registry
    type: image
  tasks:
    - name: build
      taskRef:
        name: build-docker-image
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/git-app-repo
        - name: image-tag
          value: "$(params.image-tag)"
      resources:
        inputs:
          - name: git-app-repo
            resource: git-app-repo
        outputs:
          - name: container-registry
            resource: container-registry
    - name: sync-application
      taskRef:
        name: argocd-task-sync-and-wait
      runAfter:
        - build
      params:
        - name: flags
          value: --insecure